# Generated by Django 6.0.1 on 2026-01-10 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Summary'), ('member', 'Member Statement'), ('fine', 'Fine Report'), ('custom', 'Custom Report')], max_length=20)),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='html', max_length=10)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_members', models.IntegerField(default=0)),
                ('members_paid', models.IntegerField(default=0)),
                ('members_pending', models.IntegerField(default=0)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fines', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collection_rate', models.FloatField(default=0)),
                ('average_days_late', models.FloatField(default=0)),
                ('on_time_rate', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cached_summary', to='core.contributionmonth')),
            ],
            options={
                'verbose_name_plural': 'Monthly summaries',
            },
        ),
    ]
