# Generated by Django 6.0.1 on 2026-01-10 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0002_remove_monthlysummary_month_delete_generatedreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Collection Report'), ('member', 'Member Statement'), ('outstanding', 'Outstanding Payments'), ('fines', 'Fines Summary'), ('custom', 'Custom Report')], max_length=20)),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('excel', 'Excel')], default='html', max_length=10)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
